"""Property test: Illustration Quality Constraints (Property 9).

Feature: lore-multimodal-documentary-app, Property 9: Illustration Quality Constraints
Validates: Requirements 7.3

For any illustration generated by Nano_Illustrator, the resolution shall be
at minimum 1024x1024 pixels.

Strategy: Generate random concept descriptions and verify the resolution field
on every produced illustration meets the minimum.
"""

from __future__ import annotations

from unittest.mock import AsyncMock, MagicMock

import pytest
from hypothesis import given, settings, HealthCheck
from hypothesis import strategies as st

from backend.services.nano_illustrator.illustrator import NanoIllustrator
from backend.services.nano_illustrator.models import (
    ConceptDescription,
    DepthLevel,
    VisualStyle,
)


# ── Strategies ────────────────────────────────────────────────────────────────

concept_strategy = st.builds(
    ConceptDescription,
    prompt=st.text(min_size=5, max_size=200, alphabet=st.characters(whitelist_categories=("L", "N", "P", "Z"))),
    complexity=st.sampled_from(list(DepthLevel)),
    aspect_ratio=st.sampled_from(["1:1", "16:9", "3:4", "4:3"]),
    style_override=st.one_of(st.none(), st.sampled_from(list(VisualStyle))),
)


def _make_mock_client() -> MagicMock:
    """Mock client returning a valid image response."""
    client = MagicMock()

    inline_data = MagicMock()
    inline_data.data = b"\x89PNG" + b"\x00" * 200
    inline_data.mime_type = "image/png"

    part = MagicMock()
    part.inline_data = inline_data

    content = MagicMock()
    content.parts = [part]

    candidate = MagicMock()
    candidate.content = content

    response = MagicMock()
    response.candidates = [candidate]

    client.aio.models.generate_content = AsyncMock(return_value=response)
    return client


def _parse_resolution(res_str: str) -> tuple[int, int]:
    """Parse '1024x1024' → (1024, 1024)."""
    w, h = res_str.lower().split("x")
    return int(w), int(h)


# ── Property 9: Illustration Quality Constraints ─────────────────────────────


@given(concept=concept_strategy)
@settings(max_examples=100, deadline=5000, suppress_health_check=[HealthCheck.function_scoped_fixture])
@pytest.mark.asyncio
async def test_illustration_minimum_resolution(concept: ConceptDescription):
    """Property 9: For any illustration, resolution SHALL be minimum 1024x1024.

    Feature: lore-multimodal-documentary-app, Property 9: Illustration Quality Constraints
    """
    client = _make_mock_client()
    illustrator = NanoIllustrator(client=client)

    result = await illustrator.generate_illustration(concept, session_id="qual_test")

    if result.error is None:
        w, h = _parse_resolution(result.illustration.resolution)
        assert w >= 1024, f"Width {w} < 1024"
        assert h >= 1024, f"Height {h} < 1024"
        assert result.illustration.mime_type in ("image/png", "image/jpeg", "image/webp")


@given(concept=concept_strategy)
@settings(max_examples=100, deadline=5000, suppress_health_check=[HealthCheck.function_scoped_fixture])
@pytest.mark.asyncio
async def test_illustration_has_image_data(concept: ConceptDescription):
    """Successful illustrations always have image data bytes."""
    client = _make_mock_client()
    illustrator = NanoIllustrator(client=client)

    result = await illustrator.generate_illustration(concept, session_id="qual_test2")

    if result.error is None:
        assert result.illustration.image_data is not None
        assert len(result.illustration.image_data) > 0
