"""Property-based tests for the Veo Generator service.

Feature: lore-multimodal-documentary-app

Covers:
  Property 6:  Video Clip Duration Constraints (Req 6.2)
  Property 7:  Video Quality Constraints (Req 6.5)
  Property 23: Graceful Video Degradation (Req 29.1)
"""

from __future__ import annotations

import asyncio
import sys
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from hypothesis import given, settings, strategies as st

# ── Mock google.genai before importing ────────────────────────────────────────

sys.modules.setdefault("google", MagicMock())
sys.modules.setdefault("google.genai", MagicMock())
sys.modules.setdefault("google.genai.types", MagicMock())

from backend.services.veo_generator.generator import VeoGenerator
from backend.services.veo_generator.models import (
    AspectRatio,
    DocumentaryContext,
    SceneDescription,
    VideoClip,
    VideoGenerationResult,
    VideoResolution,
    VideoStatus,
    VideoStyle,
)


# ── Strategies ────────────────────────────────────────────────────────────────

video_style_strategy = st.sampled_from(list(VideoStyle))
resolution_strategy = st.sampled_from([VideoResolution.FHD_1080P, VideoResolution.UHD_4K])
aspect_ratio_strategy = st.sampled_from(list(AspectRatio))
duration_strategy = st.sampled_from([4, 6, 8])

scene_strategy = st.builds(
    SceneDescription,
    prompt=st.text(min_size=1, max_size=200).filter(lambda x: x.strip()),
    duration=duration_strategy,
    style=video_style_strategy,
    aspect_ratio=aspect_ratio_strategy,
    generate_audio=st.booleans(),
    resolution=resolution_strategy,
)


def _make_completed_operation(duration: float = 8.0, uri: str = "gs://b/v.mp4"):
    """Create a mock completed operation with configurable duration."""
    video_obj = MagicMock()
    video_obj.uri = uri
    video_obj.url = None

    generated_video = MagicMock()
    generated_video.video = video_obj

    response = MagicMock()
    response.generated_videos = [generated_video]

    operation = MagicMock()
    operation.done = True
    operation.response = response
    return operation


def _make_client(operation=None):
    client = MagicMock()
    if operation is None:
        operation = _make_completed_operation()
    client.models.generate_videos.return_value = operation
    client.operations.get.return_value = operation
    return client


# ── Property 6: Video Clip Duration Constraints ─────────────────────────────
# For any video clip generated by Veo_Generator, the duration shall be
# between 8 and 60 seconds inclusive.
# Validates: Requirement 6.2


class TestProperty6_VideoDurationConstraints:
    """Property 6: Video Clip Duration Constraints.

    Feature: lore-multimodal-documentary-app, Property 6:
    For any video clip generated by Veo_Generator, the duration shall be
    between 8 and 60 seconds inclusive.
    """

    @given(scene=scene_strategy)
    @settings(max_examples=120, deadline=10000)
    def test_single_clip_duration_within_bounds(self, scene: SceneDescription):
        """Each individual clip duration is within valid Veo range (4-8s per clip)."""
        client = _make_client()
        gen = VeoGenerator(client=client)

        with patch("backend.services.veo_generator.generator.asyncio.sleep", new_callable=AsyncMock):
            result = asyncio.get_event_loop().run_until_complete(
                gen.generate_clip(scene, user_id="u1", session_id="s1")
            )

        if result.clip is not None:
            # Individual clips are 4-8 seconds
            assert 4.0 <= result.clip.duration <= 8.0, (
                f"Clip duration {result.clip.duration}s outside [4, 8] range"
            )

    @given(
        num_scenes=st.integers(min_value=1, max_value=7),
        duration=duration_strategy,
    )
    @settings(max_examples=100, deadline=30000)
    def test_scene_chain_duration_constraint(self, num_scenes: int, duration: int):
        """Scene chains total between 4 and 56 seconds (capped by 7 clips * 8s)."""
        client = _make_client()
        gen = VeoGenerator(client=client)

        scenes = [
            SceneDescription(
                prompt=f"Scene {i}",
                duration=duration,
                resolution=VideoResolution.FHD_1080P,
            )
            for i in range(num_scenes)
        ]

        with patch("backend.services.veo_generator.generator.asyncio.sleep", new_callable=AsyncMock):
            result = asyncio.get_event_loop().run_until_complete(
                gen.generate_scene_chain(scenes, user_id="u1", session_id="s1")
            )

        if result.clips:
            # Each clip duration is valid
            for clip in result.clips:
                assert clip.duration >= 4.0
                assert clip.duration <= 8.0

            # Total is sum of individual clips
            expected_total = sum(c.duration for c in result.clips)
            assert abs(result.total_duration - expected_total) < 0.01

    @given(duration=duration_strategy)
    @settings(max_examples=100, deadline=10000)
    def test_clip_duration_matches_requested(self, duration: int):
        """Generated clip duration matches the requested duration."""
        client = _make_client()
        gen = VeoGenerator(client=client)
        scene = SceneDescription(
            prompt="Test scene",
            duration=duration,
            resolution=VideoResolution.FHD_1080P,
        )

        with patch("backend.services.veo_generator.generator.asyncio.sleep", new_callable=AsyncMock):
            result = asyncio.get_event_loop().run_until_complete(
                gen.generate_clip(scene, user_id="u1", session_id="s1")
            )

        if result.clip is not None:
            assert result.clip.duration == float(duration)


# ── Property 7: Video Quality Constraints ────────────────────────────────────
# For any video clip generated by Veo_Generator, the resolution shall be
# at minimum 1080p (1920×1080 pixels).
# Validates: Requirement 6.5


class TestProperty7_VideoQualityConstraints:
    """Property 7: Video Quality Constraints.

    Feature: lore-multimodal-documentary-app, Property 7:
    For any video clip generated by Veo_Generator, the resolution shall be
    at minimum 1080p (1920x1080 pixels).
    """

    _RESOLUTION_RANK = {
        VideoResolution.HD_720P: 0,
        VideoResolution.FHD_1080P: 1,
        VideoResolution.UHD_4K: 2,
    }

    @given(scene=scene_strategy)
    @settings(max_examples=120, deadline=10000)
    def test_clip_resolution_minimum_1080p(self, scene: SceneDescription):
        """All generated clips meet the minimum 1080p resolution."""
        client = _make_client()
        gen = VeoGenerator(client=client)

        with patch("backend.services.veo_generator.generator.asyncio.sleep", new_callable=AsyncMock):
            result = asyncio.get_event_loop().run_until_complete(
                gen.generate_clip(scene, user_id="u1", session_id="s1")
            )

        if result.clip is not None:
            rank = self._RESOLUTION_RANK.get(result.clip.resolution, -1)
            min_rank = self._RESOLUTION_RANK[VideoResolution.FHD_1080P]
            assert rank >= min_rank, (
                f"Clip resolution {result.clip.resolution.value} "
                f"below minimum 1080p"
            )

    @given(
        resolution=st.sampled_from(list(VideoResolution)),
    )
    @settings(max_examples=100, deadline=10000)
    def test_validate_clip_quality_enforces_resolution(self, resolution: VideoResolution):
        """validate_clip_quality rejects clips below 1080p."""
        gen = VeoGenerator(client=MagicMock())
        clip = VideoClip(duration=8.0, resolution=resolution)

        valid = gen.validate_clip_quality(clip)
        rank = self._RESOLUTION_RANK.get(resolution, -1)
        min_rank = self._RESOLUTION_RANK[VideoResolution.FHD_1080P]

        if rank >= min_rank:
            assert valid is True
        else:
            assert valid is False

    @given(scene=scene_strategy)
    @settings(max_examples=100, deadline=10000)
    def test_clip_has_valid_format(self, scene: SceneDescription):
        """Generated clips have valid URL/URI and resolution metadata."""
        client = _make_client()
        gen = VeoGenerator(client=client)

        with patch("backend.services.veo_generator.generator.asyncio.sleep", new_callable=AsyncMock):
            result = asyncio.get_event_loop().run_until_complete(
                gen.generate_clip(scene, user_id="u1", session_id="s1")
            )

        if result.clip is not None:
            # Has a URL
            assert result.clip.url is not None or result.clip.gcs_uri is not None
            # Resolution is a valid enum
            assert result.clip.resolution in VideoResolution


# ── Property 23: Graceful Video Degradation ─────────────────────────────────
# For any Veo_Generator failure during documentary generation, the system
# shall continue the documentary stream with narration and illustrations,
# and notify the user of degraded functionality.
# Validates: Requirement 29.1


class TestProperty23_GracefulVideoDegradation:
    """Property 23: Graceful Video Degradation.

    Feature: lore-multimodal-documentary-app, Property 23:
    For any Veo_Generator failure during documentary generation, the system
    shall continue the documentary stream with narration and illustrations,
    and notify the user of degraded functionality.
    """

    @given(
        error_msg=st.text(min_size=1, max_size=100).filter(lambda x: x.strip()),
    )
    @settings(max_examples=120, deadline=10000)
    def test_any_error_returns_failed_result_not_exception(self, error_msg: str):
        """Any error produces a FAILED result, never an unhandled exception."""
        client = MagicMock()
        client.models.generate_videos.side_effect = RuntimeError(error_msg)

        gen = VeoGenerator(client=client)
        scene = SceneDescription(prompt="Test", resolution=VideoResolution.FHD_1080P)

        # Must not raise — returns fallback
        result = asyncio.get_event_loop().run_until_complete(
            gen.generate_clip(scene, user_id="u1", session_id="s1")
        )

        assert result.status == VideoStatus.FAILED
        assert result.error is not None
        assert result.clip is None

    @given(
        exc_type=st.sampled_from([
            RuntimeError, ValueError, ConnectionError, TimeoutError, OSError,
        ]),
    )
    @settings(max_examples=100, deadline=10000)
    def test_various_exception_types_handled(self, exc_type: type):
        """All common exception types are handled gracefully."""
        client = MagicMock()
        client.models.generate_videos.side_effect = exc_type("test failure")

        gen = VeoGenerator(client=client)
        scene = SceneDescription(prompt="Test", resolution=VideoResolution.FHD_1080P)

        result = asyncio.get_event_loop().run_until_complete(
            gen.generate_clip(scene, user_id="u1", session_id="s1")
        )

        assert result.status == VideoStatus.FAILED
        assert result.clip is None

    @given(num_failures=st.integers(min_value=1, max_value=10))
    @settings(max_examples=100, deadline=30000)
    def test_consecutive_failures_independent(self, num_failures: int):
        """Multiple consecutive failures don't corrupt generator state."""
        client = MagicMock()
        client.models.generate_videos.side_effect = RuntimeError("down")

        gen = VeoGenerator(client=client)

        for i in range(num_failures):
            result = asyncio.get_event_loop().run_until_complete(
                gen.generate_clip(
                    SceneDescription(prompt=f"Test {i}", resolution=VideoResolution.FHD_1080P),
                    user_id="u1",
                    session_id="s1",
                )
            )
            assert result.status == VideoStatus.FAILED
            assert result.clip is None

        # After failures, a successful call should work
        client.models.generate_videos.side_effect = None
        client.models.generate_videos.return_value = _make_completed_operation()

        with patch("backend.services.veo_generator.generator.asyncio.sleep", new_callable=AsyncMock):
            result = asyncio.get_event_loop().run_until_complete(
                gen.generate_clip(
                    SceneDescription(prompt="Recovery", resolution=VideoResolution.FHD_1080P),
                    user_id="u1",
                    session_id="s1",
                )
            )
        assert result.status == VideoStatus.COMPLETED
        assert result.clip is not None

    @given(
        num_scenes=st.integers(min_value=1, max_value=5),
    )
    @settings(max_examples=100, deadline=30000)
    def test_scene_chain_partial_failure_returns_successful_clips(self, num_scenes: int):
        """Scene chain with mixed failures returns whatever succeeded."""
        success_op = _make_completed_operation()
        fail_error = RuntimeError("fail")

        # Alternate success and failure
        side_effects = []
        for i in range(num_scenes):
            if i % 2 == 0:
                side_effects.append(success_op)
            else:
                side_effects.append(fail_error)

        client = MagicMock()
        client.models.generate_videos.side_effect = side_effects
        client.operations.get.return_value = success_op

        gen = VeoGenerator(client=client)
        scenes = [
            SceneDescription(
                prompt=f"Scene {i}",
                resolution=VideoResolution.FHD_1080P,
            )
            for i in range(num_scenes)
        ]

        with patch("backend.services.veo_generator.generator.asyncio.sleep", new_callable=AsyncMock):
            result = asyncio.get_event_loop().run_until_complete(
                gen.generate_scene_chain(scenes, user_id="u1", session_id="s1")
            )

        # Should not raise
        expected_successes = len([i for i in range(num_scenes) if i % 2 == 0])
        assert len(result.clips) == expected_successes
        assert len(result.errors) == num_scenes - expected_successes
