/// Firebase configuration for the LORE app.
///
/// This file is normally generated by the FlutterFire CLI:
///   dart pub global activate flutterfire_cli
///   flutterfire configure --project=geminiliveagent-487800
///
/// The values below come from the Firebase project set up in Task 1:
///   - Project:  geminiliveagent-487800
///   - Android:  com.lore.documentary  (appId: 1:469176118408:android:2736c8f0825026f05c833d)
///   - iOS:      com.lore.documentary
///   - Web API:  AIzaSyAfVAWEEU8xszrDhJbz7naH6E1GMGxUJd8
///
/// Replace placeholder values with the real ones from google-services.json /
/// GoogleService-Info.plist once FlutterFire CLI has been run.
library;

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS => ios,
      _ => throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.'),
    };
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfVAWEEU8xszrDhJbz7naH6E1GMGxUJd8',
    appId: '1:469176118408:android:2736c8f0825026f05c833d',
    messagingSenderId: '469176118408',
    projectId: 'geminiliveagent-487800',
    storageBucket: 'geminiliveagent-487800.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfVAWEEU8xszrDhJbz7naH6E1GMGxUJd8',
    appId: '1:469176118408:ios:PLACEHOLDER',
    messagingSenderId: '469176118408',
    projectId: 'geminiliveagent-487800',
    storageBucket: 'geminiliveagent-487800.appspot.com',
    iosBundleId: 'com.lore.documentary',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfVAWEEU8xszrDhJbz7naH6E1GMGxUJd8',
    appId: '1:469176118408:web:PLACEHOLDER',
    messagingSenderId: '469176118408',
    projectId: 'geminiliveagent-487800',
    storageBucket: 'geminiliveagent-487800.appspot.com',
  );
}
